//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vucem.Microservice.Api.VucemDigitalizacionAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/service/", ConfigurationName="VucemDigitalizacionAPI.IReceptor")]
    public interface IReceptor {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación RegistroDigitalizarDocumento no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/RegistroDigitalizarDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoResponse1 RegistroDigitalizarDocumento(Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/RegistroDigitalizarDocumento", ReplyAction="*")]
        System.Threading.Tasks.Task<Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoResponse1> RegistroDigitalizarDocumentoAsync(Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ConsultaEDocumentDigitalizarDocumento no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/ConsultaEDocumentDigitalizarDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaEDocumentDigitalizarDocumentoResponse ConsultaEDocumentDigitalizarDocumento(Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaEDocumentDigitalizarDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/ConsultaEDocumentDigitalizarDocumento", ReplyAction="*")]
        System.Threading.Tasks.Task<Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaEDocumentDigitalizarDocumentoResponse> ConsultaEDocumentDigitalizarDocumentoAsync(Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaEDocumentDigitalizarDocumentoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ConsultaTipoDeDocumento no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/ConsultaTipoDeDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoResponse1 ConsultaTipoDeDocumento(Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/ConsultaTipoDeDocumento", ReplyAction="*")]
        System.Threading.Tasks.Task<Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoResponse1> ConsultaTipoDeDocumentoAsync(Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento")]
    public partial class RegistroDigitalizarDocumentoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string correoElectronicoField;
        
        private Documento documentoField;
        
        private PeticionBase peticionBaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
                this.RaisePropertyChanged("correoElectronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Documento documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PeticionBase peticionBase {
            get {
                return this.peticionBaseField;
            }
            set {
                this.peticionBaseField = value;
                this.RaisePropertyChanged("peticionBase");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento")]
    public partial class Documento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idTipoDocumentoField;
        
        private string nombreDocumentoField;
        
        private string rfcConsultaField;
        
        private byte[] archivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int idTipoDocumento {
            get {
                return this.idTipoDocumentoField;
            }
            set {
                this.idTipoDocumentoField = value;
                this.RaisePropertyChanged("idTipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nombreDocumento {
            get {
                return this.nombreDocumentoField;
            }
            set {
                this.nombreDocumentoField = value;
                this.RaisePropertyChanged("nombreDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string rfcConsulta {
            get {
                return this.rfcConsultaField;
            }
            set {
                this.rfcConsultaField = value;
                this.RaisePropertyChanged("rfcConsulta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
                this.RaisePropertyChanged("archivo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento")]
    public partial class TipoDeDocumento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idTipoDeDocumentoField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long idTipoDeDocumento {
            get {
                return this.idTipoDeDocumentoField;
            }
            set {
                this.idTipoDeDocumentoField = value;
                this.RaisePropertyChanged("idTipoDeDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento")]
    public partial class ConsultaTipoDeDocumentoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TipoDeDocumento[] tiposDeDocumentosField;
        
        private RespuestaBase respuestaBaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tipoDeDocumento", IsNullable=false)]
        public TipoDeDocumento[] tiposDeDocumentos {
            get {
                return this.tiposDeDocumentosField;
            }
            set {
                this.tiposDeDocumentosField = value;
                this.RaisePropertyChanged("tiposDeDocumentos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RespuestaBase respuestaBase {
            get {
                return this.respuestaBaseField;
            }
            set {
                this.respuestaBaseField = value;
                this.RaisePropertyChanged("respuestaBase");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/common/ws/oxml/respuesta")]
    public partial class RespuestaBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool tieneErrorField;
        
        private string[] errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool tieneError {
            get {
                return this.tieneErrorField;
            }
            set {
                this.tieneErrorField = value;
                this.RaisePropertyChanged("tieneError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("mensaje", IsNullable=false)]
        public string[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento")]
    public partial class ConsultaTipoDeDocumentoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PeticionBase peticionBaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PeticionBase peticionBase {
            get {
                return this.peticionBaseField;
            }
            set {
                this.peticionBaseField = value;
                this.RaisePropertyChanged("peticionBase");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/common/ws/oxml/respuesta")]
    public partial class PeticionBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FirmaElectronica firmaElectronicaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FirmaElectronica firmaElectronica {
            get {
                return this.firmaElectronicaField;
            }
            set {
                this.firmaElectronicaField = value;
                this.RaisePropertyChanged("firmaElectronica");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/common/ws/oxml/respuesta")]
    public partial class FirmaElectronica : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] certificadoField;
        
        private string cadenaOriginalField;
        
        private byte[] firmaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] certificado {
            get {
                return this.certificadoField;
            }
            set {
                this.certificadoField = value;
                this.RaisePropertyChanged("certificado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cadenaOriginal {
            get {
                return this.cadenaOriginalField;
            }
            set {
                this.cadenaOriginalField = value;
                this.RaisePropertyChanged("cadenaOriginal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] firma {
            get {
                return this.firmaField;
            }
            set {
                this.firmaField = value;
                this.RaisePropertyChanged("firma");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento")]
    public partial class ConsultaDigitalizarDocumentoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroDeTramiteField;
        
        private string eDocumentField;
        
        private string cadenaOriginalField;
        
        private RespuestaBase respuestaBaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numeroDeTramite {
            get {
                return this.numeroDeTramiteField;
            }
            set {
                this.numeroDeTramiteField = value;
                this.RaisePropertyChanged("numeroDeTramite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string eDocument {
            get {
                return this.eDocumentField;
            }
            set {
                this.eDocumentField = value;
                this.RaisePropertyChanged("eDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cadenaOriginal {
            get {
                return this.cadenaOriginalField;
            }
            set {
                this.cadenaOriginalField = value;
                this.RaisePropertyChanged("cadenaOriginal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public RespuestaBase respuestaBase {
            get {
                return this.respuestaBaseField;
            }
            set {
                this.respuestaBaseField = value;
                this.RaisePropertyChanged("respuestaBase");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento")]
    public partial class ConsultaDigitalizarDocumentoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long numeroOperacionField;
        
        private PeticionBase peticionBaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long numeroOperacion {
            get {
                return this.numeroOperacionField;
            }
            set {
                this.numeroOperacionField = value;
                this.RaisePropertyChanged("numeroOperacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PeticionBase peticionBase {
            get {
                return this.peticionBaseField;
            }
            set {
                this.peticionBaseField = value;
                this.RaisePropertyChanged("peticionBase");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento")]
    public partial class AcuseDigitalizarDocumento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RespuestaBase respuestaBaseField;
        
        private long numeroOperacionField;
        
        private System.DateTime horaRecepcionField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RespuestaBase respuestaBase {
            get {
                return this.respuestaBaseField;
            }
            set {
                this.respuestaBaseField = value;
                this.RaisePropertyChanged("respuestaBase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long numeroOperacion {
            get {
                return this.numeroOperacionField;
            }
            set {
                this.numeroOperacionField = value;
                this.RaisePropertyChanged("numeroOperacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime horaRecepcion {
            get {
                return this.horaRecepcionField;
            }
            set {
                this.horaRecepcionField = value;
                this.RaisePropertyChanged("horaRecepcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento")]
    public partial class RegistroDigitalizarDocumentoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RespuestaBase respuestaBaseField;
        
        private AcuseDigitalizarDocumento acuseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RespuestaBase respuestaBase {
            get {
                return this.respuestaBaseField;
            }
            set {
                this.respuestaBaseField = value;
                this.RaisePropertyChanged("respuestaBase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AcuseDigitalizarDocumento acuse {
            get {
                return this.acuseField;
            }
            set {
                this.acuseField = value;
                this.RaisePropertyChanged("acuse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroDigitalizarDocumentoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento", Order=0)]
        public Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoRequest registroDigitalizarDocumentoServiceRequest;
        
        public RegistroDigitalizarDocumentoRequest1() {
        }
        
        public RegistroDigitalizarDocumentoRequest1(Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoRequest registroDigitalizarDocumentoServiceRequest) {
            this.registroDigitalizarDocumentoServiceRequest = registroDigitalizarDocumentoServiceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroDigitalizarDocumentoResponse1 {
        

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/", Order = 0)]
        public Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoResponse registroDigitalizarDocumentoServiceResponse;
        public RegistroDigitalizarDocumentoResponse1() {
        }
        
        public RegistroDigitalizarDocumentoResponse1(Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoResponse registroDigitalizarDocumentoServiceResponse) {
            this.registroDigitalizarDocumentoServiceResponse = registroDigitalizarDocumentoServiceResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaEDocumentDigitalizarDocumentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento", Order=0)]
        public Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaDigitalizarDocumentoRequest consultaDigitalizarDocumentoServiceRequest;
        
        public ConsultaEDocumentDigitalizarDocumentoRequest() {
        }
        
        public ConsultaEDocumentDigitalizarDocumentoRequest(Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaDigitalizarDocumentoRequest consultaDigitalizarDocumentoServiceRequest) {
            this.consultaDigitalizarDocumentoServiceRequest = consultaDigitalizarDocumentoServiceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaEDocumentDigitalizarDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento", Order=0)]
        public Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaDigitalizarDocumentoResponse consultaDigitalizarDocumentoServiceResponse;
        
        public ConsultaEDocumentDigitalizarDocumentoResponse() {
        }
        
        public ConsultaEDocumentDigitalizarDocumentoResponse(Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaDigitalizarDocumentoResponse consultaDigitalizarDocumentoServiceResponse) {
            this.consultaDigitalizarDocumentoServiceResponse = consultaDigitalizarDocumentoServiceResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaTipoDeDocumentoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoRequest consultaTipoDocumentoServiceRequest;
        
        public ConsultaTipoDeDocumentoRequest1() {
        }
        
        public ConsultaTipoDeDocumentoRequest1(Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoRequest consultaTipoDocumentoServiceRequest) {
            this.consultaTipoDocumentoServiceRequest = consultaTipoDocumentoServiceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaTipoDeDocumentoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento", Order=0)]
        public Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoResponse consultaTipoDocumentoServiceResponse;
        
        public ConsultaTipoDeDocumentoResponse1() {
        }
        
        public ConsultaTipoDeDocumentoResponse1(Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoResponse consultaTipoDocumentoServiceResponse) {
            this.consultaTipoDocumentoServiceResponse = consultaTipoDocumentoServiceResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReceptorChannel : Vucem.Microservice.Api.VucemDigitalizacionAPI.IReceptor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceptorClient : System.ServiceModel.ClientBase<Vucem.Microservice.Api.VucemDigitalizacionAPI.IReceptor>, Vucem.Microservice.Api.VucemDigitalizacionAPI.IReceptor {
        
        public ReceptorClient() {
        }
        
        public ReceptorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceptorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceptorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceptorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoResponse1 Vucem.Microservice.Api.VucemDigitalizacionAPI.IReceptor.RegistroDigitalizarDocumento(Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoRequest1 request) {
            return base.Channel.RegistroDigitalizarDocumento(request);
        }
        
        public Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoResponse RegistroDigitalizarDocumento(Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoRequest registroDigitalizarDocumentoServiceRequest) {
            Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoRequest1 inValue = new Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoRequest1();
            inValue.registroDigitalizarDocumentoServiceRequest = registroDigitalizarDocumentoServiceRequest;
            Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoResponse1 retVal = ((Vucem.Microservice.Api.VucemDigitalizacionAPI.IReceptor)(this)).RegistroDigitalizarDocumento(inValue);
            return retVal.registroDigitalizarDocumentoServiceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoResponse1> Vucem.Microservice.Api.VucemDigitalizacionAPI.IReceptor.RegistroDigitalizarDocumentoAsync(Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoRequest1 request) {
            return base.Channel.RegistroDigitalizarDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoResponse1> RegistroDigitalizarDocumentoAsync(Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoRequest registroDigitalizarDocumentoServiceRequest) {
            Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoRequest1 inValue = new Vucem.Microservice.Api.VucemDigitalizacionAPI.RegistroDigitalizarDocumentoRequest1();
            inValue.registroDigitalizarDocumentoServiceRequest = registroDigitalizarDocumentoServiceRequest;
            return ((Vucem.Microservice.Api.VucemDigitalizacionAPI.IReceptor)(this)).RegistroDigitalizarDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaEDocumentDigitalizarDocumentoResponse Vucem.Microservice.Api.VucemDigitalizacionAPI.IReceptor.ConsultaEDocumentDigitalizarDocumento(Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaEDocumentDigitalizarDocumentoRequest request) {
            return base.Channel.ConsultaEDocumentDigitalizarDocumento(request);
        }
        
        public Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaDigitalizarDocumentoResponse ConsultaEDocumentDigitalizarDocumento(Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaDigitalizarDocumentoRequest consultaDigitalizarDocumentoServiceRequest) {
            Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaEDocumentDigitalizarDocumentoRequest inValue = new Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaEDocumentDigitalizarDocumentoRequest();
            inValue.consultaDigitalizarDocumentoServiceRequest = consultaDigitalizarDocumentoServiceRequest;
            Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaEDocumentDigitalizarDocumentoResponse retVal = ((Vucem.Microservice.Api.VucemDigitalizacionAPI.IReceptor)(this)).ConsultaEDocumentDigitalizarDocumento(inValue);
            return retVal.consultaDigitalizarDocumentoServiceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaEDocumentDigitalizarDocumentoResponse> Vucem.Microservice.Api.VucemDigitalizacionAPI.IReceptor.ConsultaEDocumentDigitalizarDocumentoAsync(Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaEDocumentDigitalizarDocumentoRequest request) {
            return base.Channel.ConsultaEDocumentDigitalizarDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaEDocumentDigitalizarDocumentoResponse> ConsultaEDocumentDigitalizarDocumentoAsync(Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaDigitalizarDocumentoRequest consultaDigitalizarDocumentoServiceRequest) {
            Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaEDocumentDigitalizarDocumentoRequest inValue = new Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaEDocumentDigitalizarDocumentoRequest();
            inValue.consultaDigitalizarDocumentoServiceRequest = consultaDigitalizarDocumentoServiceRequest;
            return ((Vucem.Microservice.Api.VucemDigitalizacionAPI.IReceptor)(this)).ConsultaEDocumentDigitalizarDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoResponse1 Vucem.Microservice.Api.VucemDigitalizacionAPI.IReceptor.ConsultaTipoDeDocumento(Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoRequest1 request) {
            return base.Channel.ConsultaTipoDeDocumento(request);
        }
        
        public Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoResponse ConsultaTipoDeDocumento(Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoRequest consultaTipoDocumentoServiceRequest) {
            Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoRequest1 inValue = new Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoRequest1();
            inValue.consultaTipoDocumentoServiceRequest = consultaTipoDocumentoServiceRequest;
            Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoResponse1 retVal = ((Vucem.Microservice.Api.VucemDigitalizacionAPI.IReceptor)(this)).ConsultaTipoDeDocumento(inValue);
            return retVal.consultaTipoDocumentoServiceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoResponse1> Vucem.Microservice.Api.VucemDigitalizacionAPI.IReceptor.ConsultaTipoDeDocumentoAsync(Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoRequest1 request) {
            return base.Channel.ConsultaTipoDeDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoResponse1> ConsultaTipoDeDocumentoAsync(Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoRequest consultaTipoDocumentoServiceRequest) {
            Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoRequest1 inValue = new Vucem.Microservice.Api.VucemDigitalizacionAPI.ConsultaTipoDeDocumentoRequest1();
            inValue.consultaTipoDocumentoServiceRequest = consultaTipoDocumentoServiceRequest;
            return ((Vucem.Microservice.Api.VucemDigitalizacionAPI.IReceptor)(this)).ConsultaTipoDeDocumentoAsync(inValue);
        }
    }
}
