//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vucem.Microservice.Api.VucemIngresoAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx", ConfigurationName="VucemIngresoAPI.IngresoManifestacionRemote")]
    public interface IngresoManifestacionRemote {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx/IngresoMa" +
            "nifestacionRemote/registroManifestacionRequest", ReplyAction="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx/IngresoMa" +
            "nifestacionRemote/registroManifestacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Vucem.Microservice.Api.VucemIngresoAPI.registroManifestacionResponse registroManifestacion(Vucem.Microservice.Api.VucemIngresoAPI.registroManifestacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx/IngresoMa" +
            "nifestacionRemote/registroManifestacionRequest", ReplyAction="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx/IngresoMa" +
            "nifestacionRemote/registroManifestacionResponse")]
        System.Threading.Tasks.Task<Vucem.Microservice.Api.VucemIngresoAPI.registroManifestacionResponse> registroManifestacionAsync(Vucem.Microservice.Api.VucemIngresoAPI.registroManifestacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx/IngresoMa" +
            "nifestacionRemote/actualizarManifestacionRequest", ReplyAction="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx/IngresoMa" +
            "nifestacionRemote/actualizarManifestacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Vucem.Microservice.Api.VucemIngresoAPI.actualizarManifestacionResponse actualizarManifestacion(Vucem.Microservice.Api.VucemIngresoAPI.actualizarManifestacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx/IngresoMa" +
            "nifestacionRemote/actualizarManifestacionRequest", ReplyAction="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx/IngresoMa" +
            "nifestacionRemote/actualizarManifestacionResponse")]
        System.Threading.Tasks.Task<Vucem.Microservice.Api.VucemIngresoAPI.actualizarManifestacionResponse> actualizarManifestacionAsync(Vucem.Microservice.Api.VucemIngresoAPI.actualizarManifestacionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class InformacionManifestacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FirmaElectronica firmaElectronicaField;
        
        private ImportadorExportador importadorexportadorField;
        
        private DatosManifestacionValor datosManifestacionValorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FirmaElectronica firmaElectronica {
            get {
                return this.firmaElectronicaField;
            }
            set {
                this.firmaElectronicaField = value;
                this.RaisePropertyChanged("firmaElectronica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("importador-exportador", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ImportadorExportador importadorexportador {
            get {
                return this.importadorexportadorField;
            }
            set {
                this.importadorexportadorField = value;
                this.RaisePropertyChanged("importadorexportador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DatosManifestacionValor datosManifestacionValor {
            get {
                return this.datosManifestacionValorField;
            }
            set {
                this.datosManifestacionValorField = value;
                this.RaisePropertyChanged("datosManifestacionValor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class FirmaElectronica : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] certificadoField;
        
        private string cadenaOriginalField;
        
        private byte[] firmaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] certificado {
            get {
                return this.certificadoField;
            }
            set {
                this.certificadoField = value;
                this.RaisePropertyChanged("certificado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cadenaOriginal {
            get {
                return this.cadenaOriginalField;
            }
            set {
                this.cadenaOriginalField = value;
                this.RaisePropertyChanged("cadenaOriginal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] firma {
            get {
                return this.firmaField;
            }
            set {
                this.firmaField = value;
                this.RaisePropertyChanged("firma");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class respuestaActualizarManifestacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MensajeRespuesta[] mensajeField;
        
        private string mensajeActualizarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensaje", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public MensajeRespuesta[] mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensajeActualizar {
            get {
                return this.mensajeActualizarField;
            }
            set {
                this.mensajeActualizarField = value;
                this.RaisePropertyChanged("mensajeActualizar");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class MensajeRespuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoErrorField;
        
        private string descripcionErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("codigoError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("descripcionError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class DatosActualizarManifestacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroMVField;
        
        private string[] documentosField;
        
        private PersonaConsulta[] personasConsultaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numeroMV {
            get {
                return this.numeroMVField;
            }
            set {
                this.numeroMVField = value;
                this.RaisePropertyChanged("numeroMV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("eDocument", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] documentos {
            get {
                return this.documentosField;
            }
            set {
                this.documentosField = value;
                this.RaisePropertyChanged("documentos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("personaConsulta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public PersonaConsulta[] personasConsulta {
            get {
                return this.personasConsultaField;
            }
            set {
                this.personasConsultaField = value;
                this.RaisePropertyChanged("personasConsulta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class PersonaConsulta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rfcField;
        
        private string tipoFiguraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rfc {
            get {
                return this.rfcField;
            }
            set {
                this.rfcField = value;
                this.RaisePropertyChanged("rfc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tipoFigura {
            get {
                return this.tipoFiguraField;
            }
            set {
                this.tipoFiguraField = value;
                this.RaisePropertyChanged("tipoFigura");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class InformacionActualizarManifestacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FirmaElectronica firmaElectronicaField;
        
        private DatosActualizarManifestacion datosActualizarManifestacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FirmaElectronica firmaElectronica {
            get {
                return this.firmaElectronicaField;
            }
            set {
                this.firmaElectronicaField = value;
                this.RaisePropertyChanged("firmaElectronica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DatosActualizarManifestacion datosActualizarManifestacion {
            get {
                return this.datosActualizarManifestacionField;
            }
            set {
                this.datosActualizarManifestacionField = value;
                this.RaisePropertyChanged("datosActualizarManifestacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class respuestaManifestacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MensajeRespuesta[] mensajeField;
        
        private long numeroOperacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensaje", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public MensajeRespuesta[] mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long numeroOperacion {
            get {
                return this.numeroOperacionField;
            }
            set {
                this.numeroOperacionField = value;
                this.RaisePropertyChanged("numeroOperacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class ValorEnAduana : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal totalPrecioPagadoField;
        
        private decimal totalPrecioPorPagarField;
        
        private decimal totalIncrementablesField;
        
        private decimal totalDecrementablesField;
        
        private decimal totalValorAduanaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal totalPrecioPagado {
            get {
                return this.totalPrecioPagadoField;
            }
            set {
                this.totalPrecioPagadoField = value;
                this.RaisePropertyChanged("totalPrecioPagado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal totalPrecioPorPagar {
            get {
                return this.totalPrecioPorPagarField;
            }
            set {
                this.totalPrecioPorPagarField = value;
                this.RaisePropertyChanged("totalPrecioPorPagar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal totalIncrementables {
            get {
                return this.totalIncrementablesField;
            }
            set {
                this.totalIncrementablesField = value;
                this.RaisePropertyChanged("totalIncrementables");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal totalDecrementables {
            get {
                return this.totalDecrementablesField;
            }
            set {
                this.totalDecrementablesField = value;
                this.RaisePropertyChanged("totalDecrementables");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal totalValorAduana {
            get {
                return this.totalValorAduanaField;
            }
            set {
                this.totalValorAduanaField = value;
                this.RaisePropertyChanged("totalValorAduana");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class Decrementables : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoDecrementableField;
        
        private System.DateTime fechaErogacionField;
        
        private decimal importeField;
        
        private string tipoMonedaField;
        
        private decimal tipoCambioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tipoDecrementable {
            get {
                return this.tipoDecrementableField;
            }
            set {
                this.tipoDecrementableField = value;
                this.RaisePropertyChanged("tipoDecrementable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaErogacion {
            get {
                return this.fechaErogacionField;
            }
            set {
                this.fechaErogacionField = value;
                this.RaisePropertyChanged("fechaErogacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
                this.RaisePropertyChanged("importe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoMoneda {
            get {
                return this.tipoMonedaField;
            }
            set {
                this.tipoMonedaField = value;
                this.RaisePropertyChanged("tipoMoneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal tipoCambio {
            get {
                return this.tipoCambioField;
            }
            set {
                this.tipoCambioField = value;
                this.RaisePropertyChanged("tipoCambio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class Incrementables : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoIncrementableField;
        
        private System.DateTime fechaErogacionField;
        
        private decimal importeField;
        
        private string tipoMonedaField;
        
        private decimal tipoCambioField;
        
        private long aCargoImportadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tipoIncrementable {
            get {
                return this.tipoIncrementableField;
            }
            set {
                this.tipoIncrementableField = value;
                this.RaisePropertyChanged("tipoIncrementable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaErogacion {
            get {
                return this.fechaErogacionField;
            }
            set {
                this.fechaErogacionField = value;
                this.RaisePropertyChanged("fechaErogacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
                this.RaisePropertyChanged("importe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoMoneda {
            get {
                return this.tipoMonedaField;
            }
            set {
                this.tipoMonedaField = value;
                this.RaisePropertyChanged("tipoMoneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal tipoCambio {
            get {
                return this.tipoCambioField;
            }
            set {
                this.tipoCambioField = value;
                this.RaisePropertyChanged("tipoCambio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long aCargoImportador {
            get {
                return this.aCargoImportadorField;
            }
            set {
                this.aCargoImportadorField = value;
                this.RaisePropertyChanged("aCargoImportador");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class CompensoPago : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoPagoField;
        
        private System.DateTime fechaField;
        
        private string motivoField;
        
        private string prestacionMercanciaField;
        
        private string especifiqueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tipoPago {
            get {
                return this.tipoPagoField;
            }
            set {
                this.tipoPagoField = value;
                this.RaisePropertyChanged("tipoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
                this.RaisePropertyChanged("motivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string prestacionMercancia {
            get {
                return this.prestacionMercanciaField;
            }
            set {
                this.prestacionMercanciaField = value;
                this.RaisePropertyChanged("prestacionMercancia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string especifique {
            get {
                return this.especifiqueField;
            }
            set {
                this.especifiqueField = value;
                this.RaisePropertyChanged("especifique");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class PrecioPorPagar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaPagoField;
        
        private decimal totalField;
        
        private string situacionNofechaPagoField;
        
        private string tipoPagoField;
        
        private string especifiqueField;
        
        private string tipoMonedaField;
        
        private decimal tipoCambioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaPago {
            get {
                return this.fechaPagoField;
            }
            set {
                this.fechaPagoField = value;
                this.RaisePropertyChanged("fechaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string situacionNofechaPago {
            get {
                return this.situacionNofechaPagoField;
            }
            set {
                this.situacionNofechaPagoField = value;
                this.RaisePropertyChanged("situacionNofechaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoPago {
            get {
                return this.tipoPagoField;
            }
            set {
                this.tipoPagoField = value;
                this.RaisePropertyChanged("tipoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string especifique {
            get {
                return this.especifiqueField;
            }
            set {
                this.especifiqueField = value;
                this.RaisePropertyChanged("especifique");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tipoMoneda {
            get {
                return this.tipoMonedaField;
            }
            set {
                this.tipoMonedaField = value;
                this.RaisePropertyChanged("tipoMoneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal tipoCambio {
            get {
                return this.tipoCambioField;
            }
            set {
                this.tipoCambioField = value;
                this.RaisePropertyChanged("tipoCambio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class PrecioPagado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaPagoField;
        
        private decimal totalField;
        
        private string tipoPagoField;
        
        private string especifiqueField;
        
        private string tipoMonedaField;
        
        private decimal tipoCambioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaPago {
            get {
                return this.fechaPagoField;
            }
            set {
                this.fechaPagoField = value;
                this.RaisePropertyChanged("fechaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tipoPago {
            get {
                return this.tipoPagoField;
            }
            set {
                this.tipoPagoField = value;
                this.RaisePropertyChanged("tipoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string especifique {
            get {
                return this.especifiqueField;
            }
            set {
                this.especifiqueField = value;
                this.RaisePropertyChanged("especifique");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string tipoMoneda {
            get {
                return this.tipoMonedaField;
            }
            set {
                this.tipoMonedaField = value;
                this.RaisePropertyChanged("tipoMoneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal tipoCambio {
            get {
                return this.tipoCambioField;
            }
            set {
                this.tipoCambioField = value;
                this.RaisePropertyChanged("tipoCambio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class Pedimento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pedimentoField;
        
        private string patenteField;
        
        private string aduanaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string pedimento {
            get {
                return this.pedimentoField;
            }
            set {
                this.pedimentoField = value;
                this.RaisePropertyChanged("pedimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string patente {
            get {
                return this.patenteField;
            }
            set {
                this.patenteField = value;
                this.RaisePropertyChanged("patente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string aduana {
            get {
                return this.aduanaField;
            }
            set {
                this.aduanaField = value;
                this.RaisePropertyChanged("aduana");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class InformacionCove : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string coveField;
        
        private string incotermField;
        
        private long existeVinculacionField;
        
        private Pedimento[] pedimentoField;
        
        private PrecioPagado[] precioPagadoField;
        
        private PrecioPorPagar[] precioPorPagarField;
        
        private CompensoPago[] compensoPagoField;
        
        private string metodoValoracionField;
        
        private Incrementables[] incrementablesField;
        
        private Decrementables[] decrementablesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cove {
            get {
                return this.coveField;
            }
            set {
                this.coveField = value;
                this.RaisePropertyChanged("cove");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string incoterm {
            get {
                return this.incotermField;
            }
            set {
                this.incotermField = value;
                this.RaisePropertyChanged("incoterm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long existeVinculacion {
            get {
                return this.existeVinculacionField;
            }
            set {
                this.existeVinculacionField = value;
                this.RaisePropertyChanged("existeVinculacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pedimento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public Pedimento[] pedimento {
            get {
                return this.pedimentoField;
            }
            set {
                this.pedimentoField = value;
                this.RaisePropertyChanged("pedimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("precioPagado", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public PrecioPagado[] precioPagado {
            get {
                return this.precioPagadoField;
            }
            set {
                this.precioPagadoField = value;
                this.RaisePropertyChanged("precioPagado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("precioPorPagar", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public PrecioPorPagar[] precioPorPagar {
            get {
                return this.precioPorPagarField;
            }
            set {
                this.precioPorPagarField = value;
                this.RaisePropertyChanged("precioPorPagar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("compensoPago", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public CompensoPago[] compensoPago {
            get {
                return this.compensoPagoField;
            }
            set {
                this.compensoPagoField = value;
                this.RaisePropertyChanged("compensoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string metodoValoracion {
            get {
                return this.metodoValoracionField;
            }
            set {
                this.metodoValoracionField = value;
                this.RaisePropertyChanged("metodoValoracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("incrementables", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public Incrementables[] incrementables {
            get {
                return this.incrementablesField;
            }
            set {
                this.incrementablesField = value;
                this.RaisePropertyChanged("incrementables");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("decrementables", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public Decrementables[] decrementables {
            get {
                return this.decrementablesField;
            }
            set {
                this.decrementablesField = value;
                this.RaisePropertyChanged("decrementables");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class Documento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eDocumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string eDocument {
            get {
                return this.eDocumentField;
            }
            set {
                this.eDocumentField = value;
                this.RaisePropertyChanged("eDocument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class DatosManifestacionValor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PersonaConsulta[] personaConsultaField;
        
        private Documento[] documentosField;
        
        private InformacionCove[] informacionCoveField;
        
        private ValorEnAduana valorEnAduanaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("personaConsulta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PersonaConsulta[] personaConsulta {
            get {
                return this.personaConsultaField;
            }
            set {
                this.personaConsultaField = value;
                this.RaisePropertyChanged("personaConsulta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("documentos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Documento[] documentos {
            get {
                return this.documentosField;
            }
            set {
                this.documentosField = value;
                this.RaisePropertyChanged("documentos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("informacionCove", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public InformacionCove[] informacionCove {
            get {
                return this.informacionCoveField;
            }
            set {
                this.informacionCoveField = value;
                this.RaisePropertyChanged("informacionCove");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ValorEnAduana valorEnAduana {
            get {
                return this.valorEnAduanaField;
            }
            set {
                this.valorEnAduanaField = value;
                this.RaisePropertyChanged("valorEnAduana");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class ImportadorExportador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rfcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rfc {
            get {
                return this.rfcField;
            }
            set {
                this.rfcField = value;
                this.RaisePropertyChanged("rfc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registroManifestacion", WrapperNamespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx", IsWrapped=true)]
    public partial class registroManifestacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Vucem.Microservice.Api.VucemIngresoAPI.InformacionManifestacion informacionManifestacion;
        
        public registroManifestacionRequest() {
        }
        
        public registroManifestacionRequest(Vucem.Microservice.Api.VucemIngresoAPI.InformacionManifestacion informacionManifestacion) {
            this.informacionManifestacion = informacionManifestacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registroManifestacionResponse", WrapperNamespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx", IsWrapped=true)]
    public partial class registroManifestacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Vucem.Microservice.Api.VucemIngresoAPI.respuestaManifestacion @return;
        
        public registroManifestacionResponse() {
        }
        
        public registroManifestacionResponse(Vucem.Microservice.Api.VucemIngresoAPI.respuestaManifestacion @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarManifestacion", WrapperNamespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx", IsWrapped=true)]
    public partial class actualizarManifestacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Vucem.Microservice.Api.VucemIngresoAPI.InformacionActualizarManifestacion informacionActualizarManifestacion;
        
        public actualizarManifestacionRequest() {
        }
        
        public actualizarManifestacionRequest(Vucem.Microservice.Api.VucemIngresoAPI.InformacionActualizarManifestacion informacionActualizarManifestacion) {
            this.informacionActualizarManifestacion = informacionActualizarManifestacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarManifestacionResponse", WrapperNamespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx", IsWrapped=true)]
    public partial class actualizarManifestacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.ingresomanifestacion.manifestacion.www.ventanillaunica.gob.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Vucem.Microservice.Api.VucemIngresoAPI.respuestaActualizarManifestacion @return;
        
        public actualizarManifestacionResponse() {
        }
        
        public actualizarManifestacionResponse(Vucem.Microservice.Api.VucemIngresoAPI.respuestaActualizarManifestacion @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IngresoManifestacionRemoteChannel : Vucem.Microservice.Api.VucemIngresoAPI.IngresoManifestacionRemote, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IngresoManifestacionRemoteClient : System.ServiceModel.ClientBase<Vucem.Microservice.Api.VucemIngresoAPI.IngresoManifestacionRemote>, Vucem.Microservice.Api.VucemIngresoAPI.IngresoManifestacionRemote {
        
        public IngresoManifestacionRemoteClient() {
        }
        
        public IngresoManifestacionRemoteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IngresoManifestacionRemoteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IngresoManifestacionRemoteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IngresoManifestacionRemoteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vucem.Microservice.Api.VucemIngresoAPI.registroManifestacionResponse Vucem.Microservice.Api.VucemIngresoAPI.IngresoManifestacionRemote.registroManifestacion(Vucem.Microservice.Api.VucemIngresoAPI.registroManifestacionRequest request) {
            return base.Channel.registroManifestacion(request);
        }
        
        public Vucem.Microservice.Api.VucemIngresoAPI.respuestaManifestacion registroManifestacion(Vucem.Microservice.Api.VucemIngresoAPI.InformacionManifestacion informacionManifestacion) {
            Vucem.Microservice.Api.VucemIngresoAPI.registroManifestacionRequest inValue = new Vucem.Microservice.Api.VucemIngresoAPI.registroManifestacionRequest();
            inValue.informacionManifestacion = informacionManifestacion;
            Vucem.Microservice.Api.VucemIngresoAPI.registroManifestacionResponse retVal = ((Vucem.Microservice.Api.VucemIngresoAPI.IngresoManifestacionRemote)(this)).registroManifestacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vucem.Microservice.Api.VucemIngresoAPI.registroManifestacionResponse> Vucem.Microservice.Api.VucemIngresoAPI.IngresoManifestacionRemote.registroManifestacionAsync(Vucem.Microservice.Api.VucemIngresoAPI.registroManifestacionRequest request) {
            return base.Channel.registroManifestacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vucem.Microservice.Api.VucemIngresoAPI.registroManifestacionResponse> registroManifestacionAsync(Vucem.Microservice.Api.VucemIngresoAPI.InformacionManifestacion informacionManifestacion) {
            Vucem.Microservice.Api.VucemIngresoAPI.registroManifestacionRequest inValue = new Vucem.Microservice.Api.VucemIngresoAPI.registroManifestacionRequest();
            inValue.informacionManifestacion = informacionManifestacion;
            return ((Vucem.Microservice.Api.VucemIngresoAPI.IngresoManifestacionRemote)(this)).registroManifestacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vucem.Microservice.Api.VucemIngresoAPI.actualizarManifestacionResponse Vucem.Microservice.Api.VucemIngresoAPI.IngresoManifestacionRemote.actualizarManifestacion(Vucem.Microservice.Api.VucemIngresoAPI.actualizarManifestacionRequest request) {
            return base.Channel.actualizarManifestacion(request);
        }
        
        public Vucem.Microservice.Api.VucemIngresoAPI.respuestaActualizarManifestacion actualizarManifestacion(Vucem.Microservice.Api.VucemIngresoAPI.InformacionActualizarManifestacion informacionActualizarManifestacion) {
            Vucem.Microservice.Api.VucemIngresoAPI.actualizarManifestacionRequest inValue = new Vucem.Microservice.Api.VucemIngresoAPI.actualizarManifestacionRequest();
            inValue.informacionActualizarManifestacion = informacionActualizarManifestacion;
            Vucem.Microservice.Api.VucemIngresoAPI.actualizarManifestacionResponse retVal = ((Vucem.Microservice.Api.VucemIngresoAPI.IngresoManifestacionRemote)(this)).actualizarManifestacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vucem.Microservice.Api.VucemIngresoAPI.actualizarManifestacionResponse> Vucem.Microservice.Api.VucemIngresoAPI.IngresoManifestacionRemote.actualizarManifestacionAsync(Vucem.Microservice.Api.VucemIngresoAPI.actualizarManifestacionRequest request) {
            return base.Channel.actualizarManifestacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vucem.Microservice.Api.VucemIngresoAPI.actualizarManifestacionResponse> actualizarManifestacionAsync(Vucem.Microservice.Api.VucemIngresoAPI.InformacionActualizarManifestacion informacionActualizarManifestacion) {
            Vucem.Microservice.Api.VucemIngresoAPI.actualizarManifestacionRequest inValue = new Vucem.Microservice.Api.VucemIngresoAPI.actualizarManifestacionRequest();
            inValue.informacionActualizarManifestacion = informacionActualizarManifestacion;
            return ((Vucem.Microservice.Api.VucemIngresoAPI.IngresoManifestacionRemote)(this)).actualizarManifestacionAsync(inValue);
        }
    }
}
