//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vucem.Microservice.Api.VucemConsultaAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx", ConfigurationName="VucemConsultaAPI.ConsultaManifestacionRemote")]
    public interface ConsultaManifestacionRemote {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx/Consulta" +
            "ManifestacionRemote/consultaManifestacionRequest", ReplyAction="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx/Consulta" +
            "ManifestacionRemote/consultaManifestacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Vucem.Microservice.Api.VucemConsultaAPI.consultaManifestacionResponse consultaManifestacion(Vucem.Microservice.Api.VucemConsultaAPI.consultaManifestacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx/Consulta" +
            "ManifestacionRemote/consultaManifestacionRequest", ReplyAction="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx/Consulta" +
            "ManifestacionRemote/consultaManifestacionResponse")]
        System.Threading.Tasks.Task<Vucem.Microservice.Api.VucemConsultaAPI.consultaManifestacionResponse> consultaManifestacionAsync(Vucem.Microservice.Api.VucemConsultaAPI.consultaManifestacionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class datosManifestacionGeneral : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long numeroOperacionField;
        
        private bool numeroOperacionFieldSpecified;
        
        private string eDocumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long numeroOperacion {
            get {
                return this.numeroOperacionField;
            }
            set {
                this.numeroOperacionField = value;
                this.RaisePropertyChanged("numeroOperacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroOperacionSpecified {
            get {
                return this.numeroOperacionFieldSpecified;
            }
            set {
                this.numeroOperacionFieldSpecified = value;
                this.RaisePropertyChanged("numeroOperacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string eDocument {
            get {
                return this.eDocumentField;
            }
            set {
                this.eDocumentField = value;
                this.RaisePropertyChanged("eDocument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class MensajeRespuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoErrorField;
        
        private string descripcionErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("codigoError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("descripcionError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class ValorEnAduana : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal totalPrecioPagadoField;
        
        private decimal totalPrecioPorPagarField;
        
        private decimal totalIncrementablesField;
        
        private decimal totalDecrementablesField;
        
        private decimal totalValorAduanaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal totalPrecioPagado {
            get {
                return this.totalPrecioPagadoField;
            }
            set {
                this.totalPrecioPagadoField = value;
                this.RaisePropertyChanged("totalPrecioPagado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal totalPrecioPorPagar {
            get {
                return this.totalPrecioPorPagarField;
            }
            set {
                this.totalPrecioPorPagarField = value;
                this.RaisePropertyChanged("totalPrecioPorPagar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal totalIncrementables {
            get {
                return this.totalIncrementablesField;
            }
            set {
                this.totalIncrementablesField = value;
                this.RaisePropertyChanged("totalIncrementables");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal totalDecrementables {
            get {
                return this.totalDecrementablesField;
            }
            set {
                this.totalDecrementablesField = value;
                this.RaisePropertyChanged("totalDecrementables");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal totalValorAduana {
            get {
                return this.totalValorAduanaField;
            }
            set {
                this.totalValorAduanaField = value;
                this.RaisePropertyChanged("totalValorAduana");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class Decrementables : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoDecrementableField;
        
        private System.DateTime fechaErogacionField;
        
        private decimal importeField;
        
        private string tipoMonedaField;
        
        private decimal tipoCambioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tipoDecrementable {
            get {
                return this.tipoDecrementableField;
            }
            set {
                this.tipoDecrementableField = value;
                this.RaisePropertyChanged("tipoDecrementable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaErogacion {
            get {
                return this.fechaErogacionField;
            }
            set {
                this.fechaErogacionField = value;
                this.RaisePropertyChanged("fechaErogacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
                this.RaisePropertyChanged("importe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoMoneda {
            get {
                return this.tipoMonedaField;
            }
            set {
                this.tipoMonedaField = value;
                this.RaisePropertyChanged("tipoMoneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal tipoCambio {
            get {
                return this.tipoCambioField;
            }
            set {
                this.tipoCambioField = value;
                this.RaisePropertyChanged("tipoCambio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class Incrementables : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoIncrementableField;
        
        private System.DateTime fechaErogacionField;
        
        private decimal importeField;
        
        private string tipoMonedaField;
        
        private decimal tipoCambioField;
        
        private long aCargoImportadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tipoIncrementable {
            get {
                return this.tipoIncrementableField;
            }
            set {
                this.tipoIncrementableField = value;
                this.RaisePropertyChanged("tipoIncrementable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaErogacion {
            get {
                return this.fechaErogacionField;
            }
            set {
                this.fechaErogacionField = value;
                this.RaisePropertyChanged("fechaErogacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
                this.RaisePropertyChanged("importe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoMoneda {
            get {
                return this.tipoMonedaField;
            }
            set {
                this.tipoMonedaField = value;
                this.RaisePropertyChanged("tipoMoneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal tipoCambio {
            get {
                return this.tipoCambioField;
            }
            set {
                this.tipoCambioField = value;
                this.RaisePropertyChanged("tipoCambio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long aCargoImportador {
            get {
                return this.aCargoImportadorField;
            }
            set {
                this.aCargoImportadorField = value;
                this.RaisePropertyChanged("aCargoImportador");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class CompensoPago : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoPagoField;
        
        private System.DateTime fechaField;
        
        private string motivoField;
        
        private string prestacionMercanciaField;
        
        private string especifiqueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tipoPago {
            get {
                return this.tipoPagoField;
            }
            set {
                this.tipoPagoField = value;
                this.RaisePropertyChanged("tipoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
                this.RaisePropertyChanged("motivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string prestacionMercancia {
            get {
                return this.prestacionMercanciaField;
            }
            set {
                this.prestacionMercanciaField = value;
                this.RaisePropertyChanged("prestacionMercancia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string especifique {
            get {
                return this.especifiqueField;
            }
            set {
                this.especifiqueField = value;
                this.RaisePropertyChanged("especifique");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class PrecioPorPagar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaPagoField;
        
        private decimal totalField;
        
        private string situacionNofechaPagoField;
        
        private string tipoPagoField;
        
        private string especifiqueField;
        
        private string tipoMonedaField;
        
        private decimal tipoCambioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaPago {
            get {
                return this.fechaPagoField;
            }
            set {
                this.fechaPagoField = value;
                this.RaisePropertyChanged("fechaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string situacionNofechaPago {
            get {
                return this.situacionNofechaPagoField;
            }
            set {
                this.situacionNofechaPagoField = value;
                this.RaisePropertyChanged("situacionNofechaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoPago {
            get {
                return this.tipoPagoField;
            }
            set {
                this.tipoPagoField = value;
                this.RaisePropertyChanged("tipoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string especifique {
            get {
                return this.especifiqueField;
            }
            set {
                this.especifiqueField = value;
                this.RaisePropertyChanged("especifique");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tipoMoneda {
            get {
                return this.tipoMonedaField;
            }
            set {
                this.tipoMonedaField = value;
                this.RaisePropertyChanged("tipoMoneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal tipoCambio {
            get {
                return this.tipoCambioField;
            }
            set {
                this.tipoCambioField = value;
                this.RaisePropertyChanged("tipoCambio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class PrecioPagado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaPagoField;
        
        private decimal totalField;
        
        private string tipoPagoField;
        
        private string especifiqueField;
        
        private string tipoMonedaField;
        
        private decimal tipoCambioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaPago {
            get {
                return this.fechaPagoField;
            }
            set {
                this.fechaPagoField = value;
                this.RaisePropertyChanged("fechaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tipoPago {
            get {
                return this.tipoPagoField;
            }
            set {
                this.tipoPagoField = value;
                this.RaisePropertyChanged("tipoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string especifique {
            get {
                return this.especifiqueField;
            }
            set {
                this.especifiqueField = value;
                this.RaisePropertyChanged("especifique");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string tipoMoneda {
            get {
                return this.tipoMonedaField;
            }
            set {
                this.tipoMonedaField = value;
                this.RaisePropertyChanged("tipoMoneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal tipoCambio {
            get {
                return this.tipoCambioField;
            }
            set {
                this.tipoCambioField = value;
                this.RaisePropertyChanged("tipoCambio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class Pedimento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pedimentoField;
        
        private string patenteField;
        
        private string aduanaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string pedimento {
            get {
                return this.pedimentoField;
            }
            set {
                this.pedimentoField = value;
                this.RaisePropertyChanged("pedimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string patente {
            get {
                return this.patenteField;
            }
            set {
                this.patenteField = value;
                this.RaisePropertyChanged("patente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string aduana {
            get {
                return this.aduanaField;
            }
            set {
                this.aduanaField = value;
                this.RaisePropertyChanged("aduana");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class InformacionCove : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string coveField;
        
        private string incotermField;
        
        private long existeVinculacionField;
        
        private Pedimento[] pedimentoField;
        
        private PrecioPagado[] precioPagadoField;
        
        private PrecioPorPagar[] precioPorPagarField;
        
        private CompensoPago[] compensoPagoField;
        
        private string metodoValoracionField;
        
        private Incrementables[] incrementablesField;
        
        private Decrementables[] decrementablesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cove {
            get {
                return this.coveField;
            }
            set {
                this.coveField = value;
                this.RaisePropertyChanged("cove");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string incoterm {
            get {
                return this.incotermField;
            }
            set {
                this.incotermField = value;
                this.RaisePropertyChanged("incoterm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long existeVinculacion {
            get {
                return this.existeVinculacionField;
            }
            set {
                this.existeVinculacionField = value;
                this.RaisePropertyChanged("existeVinculacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pedimento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public Pedimento[] pedimento {
            get {
                return this.pedimentoField;
            }
            set {
                this.pedimentoField = value;
                this.RaisePropertyChanged("pedimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("precioPagado", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public PrecioPagado[] precioPagado {
            get {
                return this.precioPagadoField;
            }
            set {
                this.precioPagadoField = value;
                this.RaisePropertyChanged("precioPagado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("precioPorPagar", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public PrecioPorPagar[] precioPorPagar {
            get {
                return this.precioPorPagarField;
            }
            set {
                this.precioPorPagarField = value;
                this.RaisePropertyChanged("precioPorPagar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("compensoPago", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public CompensoPago[] compensoPago {
            get {
                return this.compensoPagoField;
            }
            set {
                this.compensoPagoField = value;
                this.RaisePropertyChanged("compensoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string metodoValoracion {
            get {
                return this.metodoValoracionField;
            }
            set {
                this.metodoValoracionField = value;
                this.RaisePropertyChanged("metodoValoracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("incrementables", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public Incrementables[] incrementables {
            get {
                return this.incrementablesField;
            }
            set {
                this.incrementablesField = value;
                this.RaisePropertyChanged("incrementables");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("decrementables", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public Decrementables[] decrementables {
            get {
                return this.decrementablesField;
            }
            set {
                this.decrementablesField = value;
                this.RaisePropertyChanged("decrementables");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class Documento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eDocumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string eDocument {
            get {
                return this.eDocumentField;
            }
            set {
                this.eDocumentField = value;
                this.RaisePropertyChanged("eDocument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class PersonaConsulta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rfcField;
        
        private string tipoFiguraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rfc {
            get {
                return this.rfcField;
            }
            set {
                this.rfcField = value;
                this.RaisePropertyChanged("rfc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tipoFigura {
            get {
                return this.tipoFiguraField;
            }
            set {
                this.tipoFiguraField = value;
                this.RaisePropertyChanged("tipoFigura");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class DatosManifestacionValor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PersonaConsulta[] personaConsultaField;
        
        private Documento[] documentosField;
        
        private InformacionCove[] informacionCoveField;
        
        private ValorEnAduana valorEnAduanaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("personaConsulta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PersonaConsulta[] personaConsulta {
            get {
                return this.personaConsultaField;
            }
            set {
                this.personaConsultaField = value;
                this.RaisePropertyChanged("personaConsulta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("documentos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Documento[] documentos {
            get {
                return this.documentosField;
            }
            set {
                this.documentosField = value;
                this.RaisePropertyChanged("documentos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("informacionCove", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public InformacionCove[] informacionCove {
            get {
                return this.informacionCoveField;
            }
            set {
                this.informacionCoveField = value;
                this.RaisePropertyChanged("informacionCove");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ValorEnAduana valorEnAduana {
            get {
                return this.valorEnAduanaField;
            }
            set {
                this.valorEnAduanaField = value;
                this.RaisePropertyChanged("valorEnAduana");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class ImportadorExportador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rfcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rfc {
            get {
                return this.rfcField;
            }
            set {
                this.rfcField = value;
                this.RaisePropertyChanged("rfc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class Solicitante : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rfcSolicitanteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rfcSolicitante {
            get {
                return this.rfcSolicitanteField;
            }
            set {
                this.rfcSolicitanteField = value;
                this.RaisePropertyChanged("rfcSolicitante");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx")]
    public partial class RespuestaConsultaGeneral : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rfcSolicitanteField;
        
        private string nombreORazonSocialSolicitanteField;
        
        private string rfcImportadorField;
        
        private string nombreORazonSocialImportadorField;
        
        private System.DateTime fechaYHoraRecepcionField;
        
        private bool fechaYHoraRecepcionFieldSpecified;
        
        private string operacionField;
        
        private string eDocumentField;
        
        private string covesField;
        
        private string selloDigitalSolicitanteField;
        
        private string selloDigitalVentanillaField;
        
        private string cadenaOriginalField;
        
        private string estatusField;
        
        private Solicitante solicitanteField;
        
        private ImportadorExportador importadorexportadorField;
        
        private DatosManifestacionValor datosManifestacionValorField;
        
        private MensajeRespuesta[] mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rfcSolicitante {
            get {
                return this.rfcSolicitanteField;
            }
            set {
                this.rfcSolicitanteField = value;
                this.RaisePropertyChanged("rfcSolicitante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombreORazonSocialSolicitante {
            get {
                return this.nombreORazonSocialSolicitanteField;
            }
            set {
                this.nombreORazonSocialSolicitanteField = value;
                this.RaisePropertyChanged("nombreORazonSocialSolicitante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string rfcImportador {
            get {
                return this.rfcImportadorField;
            }
            set {
                this.rfcImportadorField = value;
                this.RaisePropertyChanged("rfcImportador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreORazonSocialImportador {
            get {
                return this.nombreORazonSocialImportadorField;
            }
            set {
                this.nombreORazonSocialImportadorField = value;
                this.RaisePropertyChanged("nombreORazonSocialImportador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaYHoraRecepcion {
            get {
                return this.fechaYHoraRecepcionField;
            }
            set {
                this.fechaYHoraRecepcionField = value;
                this.RaisePropertyChanged("fechaYHoraRecepcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaYHoraRecepcionSpecified {
            get {
                return this.fechaYHoraRecepcionFieldSpecified;
            }
            set {
                this.fechaYHoraRecepcionFieldSpecified = value;
                this.RaisePropertyChanged("fechaYHoraRecepcionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string operacion {
            get {
                return this.operacionField;
            }
            set {
                this.operacionField = value;
                this.RaisePropertyChanged("operacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string eDocument {
            get {
                return this.eDocumentField;
            }
            set {
                this.eDocumentField = value;
                this.RaisePropertyChanged("eDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string coves {
            get {
                return this.covesField;
            }
            set {
                this.covesField = value;
                this.RaisePropertyChanged("coves");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string selloDigitalSolicitante {
            get {
                return this.selloDigitalSolicitanteField;
            }
            set {
                this.selloDigitalSolicitanteField = value;
                this.RaisePropertyChanged("selloDigitalSolicitante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string selloDigitalVentanilla {
            get {
                return this.selloDigitalVentanillaField;
            }
            set {
                this.selloDigitalVentanillaField = value;
                this.RaisePropertyChanged("selloDigitalVentanilla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string cadenaOriginal {
            get {
                return this.cadenaOriginalField;
            }
            set {
                this.cadenaOriginalField = value;
                this.RaisePropertyChanged("cadenaOriginal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("estatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public Solicitante solicitante {
            get {
                return this.solicitanteField;
            }
            set {
                this.solicitanteField = value;
                this.RaisePropertyChanged("solicitante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("importador-exportador", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public ImportadorExportador importadorexportador {
            get {
                return this.importadorexportadorField;
            }
            set {
                this.importadorexportadorField = value;
                this.RaisePropertyChanged("importadorexportador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public DatosManifestacionValor datosManifestacionValor {
            get {
                return this.datosManifestacionValorField;
            }
            set {
                this.datosManifestacionValorField = value;
                this.RaisePropertyChanged("datosManifestacionValor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensaje", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public MensajeRespuesta[] mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaManifestacion", WrapperNamespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx", IsWrapped=true)]
    public partial class consultaManifestacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Vucem.Microservice.Api.VucemConsultaAPI.datosManifestacionGeneral datosManifestacion;
        
        public consultaManifestacionRequest() {
        }
        
        public consultaManifestacionRequest(Vucem.Microservice.Api.VucemConsultaAPI.datosManifestacionGeneral datosManifestacion) {
            this.datosManifestacion = datosManifestacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaManifestacionResponse", WrapperNamespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx", IsWrapped=true)]
    public partial class consultaManifestacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.consultamanifestacion.manifestacion.www.ventanillaunica.gob.mx", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Vucem.Microservice.Api.VucemConsultaAPI.RespuestaConsultaGeneral @return;
        
        public consultaManifestacionResponse() {
        }
        
        public consultaManifestacionResponse(Vucem.Microservice.Api.VucemConsultaAPI.RespuestaConsultaGeneral @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaManifestacionRemoteChannel : Vucem.Microservice.Api.VucemConsultaAPI.ConsultaManifestacionRemote, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaManifestacionRemoteClient : System.ServiceModel.ClientBase<Vucem.Microservice.Api.VucemConsultaAPI.ConsultaManifestacionRemote>, Vucem.Microservice.Api.VucemConsultaAPI.ConsultaManifestacionRemote {
        
        public ConsultaManifestacionRemoteClient() {
        }
        
        public ConsultaManifestacionRemoteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaManifestacionRemoteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaManifestacionRemoteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaManifestacionRemoteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vucem.Microservice.Api.VucemConsultaAPI.consultaManifestacionResponse Vucem.Microservice.Api.VucemConsultaAPI.ConsultaManifestacionRemote.consultaManifestacion(Vucem.Microservice.Api.VucemConsultaAPI.consultaManifestacionRequest request) {
            return base.Channel.consultaManifestacion(request);
        }
        
        public Vucem.Microservice.Api.VucemConsultaAPI.RespuestaConsultaGeneral consultaManifestacion(Vucem.Microservice.Api.VucemConsultaAPI.datosManifestacionGeneral datosManifestacion) {
            Vucem.Microservice.Api.VucemConsultaAPI.consultaManifestacionRequest inValue = new Vucem.Microservice.Api.VucemConsultaAPI.consultaManifestacionRequest();
            inValue.datosManifestacion = datosManifestacion;
            Vucem.Microservice.Api.VucemConsultaAPI.consultaManifestacionResponse retVal = ((Vucem.Microservice.Api.VucemConsultaAPI.ConsultaManifestacionRemote)(this)).consultaManifestacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vucem.Microservice.Api.VucemConsultaAPI.consultaManifestacionResponse> Vucem.Microservice.Api.VucemConsultaAPI.ConsultaManifestacionRemote.consultaManifestacionAsync(Vucem.Microservice.Api.VucemConsultaAPI.consultaManifestacionRequest request) {
            return base.Channel.consultaManifestacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vucem.Microservice.Api.VucemConsultaAPI.consultaManifestacionResponse> consultaManifestacionAsync(Vucem.Microservice.Api.VucemConsultaAPI.datosManifestacionGeneral datosManifestacion) {
            Vucem.Microservice.Api.VucemConsultaAPI.consultaManifestacionRequest inValue = new Vucem.Microservice.Api.VucemConsultaAPI.consultaManifestacionRequest();
            inValue.datosManifestacion = datosManifestacion;
            return ((Vucem.Microservice.Api.VucemConsultaAPI.ConsultaManifestacionRemote)(this)).consultaManifestacionAsync(inValue);
        }
    }
}
